---
- name: My first playbook :)
  hosts: web-test
  sudo: true
  vars:
    common_packages:
        - vim
        - telnet
        - gcc
  tasks:
    - name: Install multiple packages
      yum: name={{item}} state=installed
      with_items: common_packages
