---
- name: My first playbook :)
  hosts: web-test
  sudo: true
  vars:
    name_to_say_hello: Pablo
  tasks:
    - name: Use template
      template: src=templates/index.html dest=/home/vagrant/index_new.html
